### PR TITLE
[CI & docs] Rework of analysis docs + improved checks

### PR DESCRIPTION
**Pull request by chalin**
- Adds markdown linter + GH action
- Runs markdown linter over all files, except old project analyses (it will check new analyses). Fixes done, and included in this PR.
- Includes result of review and slight rework of templates (a few file renames).
- Fixes broken links

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
I appreciate the time you're spending to help organize and tidy up this repo @chalin 

> Runs markdown linter over all files, except old project analyses (it will check new analyses). Fixes done, and included in this PR.

I think linting the old project analyses is a good idea too (for later).

Where do you set the targets/filters for the linter?

**Comment by chalin** [comment]
> I think linting the old project analyses is a good idea too (for later).
> 
> Where do you set the targets/filters for the linter?

In the NPM scripts.

I can't get the file filtering to work inside GH actions (it works locally), so I'm going to ignore all analyses for now.

**Comment by nate-double-u** [comment]
> I can't get the file filtering to work inside GH actions (it works locally), so I'm going to ignore all analyses for now.

@RobertKielty, maybe you could take a look?

**Comment by chalin** [comment]
All good. Checks are green. Merging.

**Pull request merged**
