### PR TITLE
Correct 2 GH IDs, and turn them all into links

### PR DESCRIPTION
**Pull request by chalin**

### CODE REVIEW

**Comment by chalin** [comment]
cc @nate-double-u

**Comment by nate-double-u** [comment]
Looks good to me.

**Comment by nate-double-u** [comment]
I'll close my PR in favour of this one.

**Comment by chalin** [comment]
Oh, apologies, I hadn't see that you had submitted a PR (and didn't see the issue either). Oops!

**Comment by nate-double-u** [comment]
No worries, I've also pointed the issue to this PR.

**Pull request merged**
