### PR TITLE
Backstage doc issues

### PR DESCRIPTION
**Pull request by dwelsch-esi**
Added backstage-issues.md, a master list of issues for the Backstage tech doc analysis and implementation.

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
Thanks for this @dwelsch-esi

**Comment by nate-double-u** [comment]
Also, i think your DCO is incorrect 

it looks like it was correct in the other PR when it was:
```
Signed-off-by: dwelsch-esi <116022979+dwelsch-esi@users.noreply.github.com>
```

It's best to correct it if possible, this'll come up over and over if we don't fix it.

Here are some instructions on how to correct it: https://github.com/cncf/techdocs/pull/204/checks?check_run_id=19074965574 (tho this will require using a terminal. If you want I can correct it here on squash).

**Comment by dwelsch-esi** [comment]
DCO fixed.

Dave

-- 
  David Welsch
  ***@***.***


On Mon, Nov 27, 2023, at 3:31 PM, Nate W wrote:
> 
> 
> Also, i think your DCO is incorrect
> 
> it looks like it was correct in the other PR when it was:
> 
> `Signed-off-by: dwelsch-esi ***@***.***>
`

**Review by nate-double-u — CHANGES_REQUESTED** [review]
I think the same thing happened here as over on this PR: https://github.com/cncf/techdocs/pull/202#issuecomment-1830385284

Let's close this, and try again with the process i describe there.

(be sure to save your changes so you can re apply them)

**Review by nate-double-u — APPROVED** [review]
Thanks for putting this together @dwelsch-esi!

**Pull request merged**
