### PR TITLE
Revisions: Backstage doc analysis and implementation plan.

### PR DESCRIPTION
**Pull request by dwelsch-esi**
Updates to README, doc analysis, and implementation plan.

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
Good updates, thx!

**Comment by nate-double-u** [comment]
Looking at this set of commits, this doesn't look quite right. Are the results (files changed) what you want @dwelsch-esi?

**Comment by dwelsch-esi** [comment]
@nate-double-u The file changes are correct. I think the way I'm working on a branch in my fork is polluting the commit history. I'm not very good with Git, I'm afraid.

**Comment by nate-double-u** [comment]
I think i know what happened -- because i squashed the original all the individual commits got combined. You likely didn't pull those changes down, or create a new branch from main for these changes, so you're working off your old branch (with all those original commits).

So, when a PR gets merged in, it's best practice to delete the branch that was merged. Then, if you want to make new changes, make sure your fork is up to date with `main`, make a new branch, make your changes, then create a new PR with the new branch.

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Let's close this one, and try again using the process i describe above

**Comment by dwelsch-esi** [comment]
Closing. Will re-submit with a clean commit history.

**Pull request closed without merging**
