### PR TITLE
Backstage issues

### PR DESCRIPTION
**Pull request by dwelsch-esi**
Adding a master list of Backstage tech doc issues.

### CODE REVIEW

**Comment by nate-double-u** [comment]
I'm not sure why all the files in this folder are getting changed. I think we should only be adding the issues files, correct?

**Comment by dwelsch-esi** [comment]
Correct. I couldn't figure out what's going on there. I created a branch in my own fork and pulled cncf/main into it before I added the issues file and did the PR, so there shouldn't be any other different files. The only thing I can think of that might have happened is that I did a squash merge, which might have created a new commit that's confusing things. If you want, we can close the PR and try again without the squash? 

-- 
  David Welsch
  ***@***.***

**Comment by nate-double-u** [comment]
remember to make sure your branch is up to date with the upstream repo

**Comment by dwelsch-esi** [comment]
This looks better. There's only one new file.

https://github.com/cncf/techdocs/pull/204

Dave

-- 
  David Welsch
  ***@***.***

**Pull request closed without merging**
